version: '3.1'

services:
  mysql:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "cbaz6173"
      MYSQL_DATABASE: "library"
    ports:
      - "3306:3306"
    volumes:
      - "libmysql:/var/lib/mysql"
volumes:
  libmysql: